version: '3.7'

#Для запуска https сперва нужно сгенерировать сертификат запустив эти команды
#dotnet dev-certs https -ep %USERPROFILE%\.aspnet\https\aspnetapp.pfx -p DeeFlatPassword 
#dotnet dev-certs https --trust     
services:
  webapp:
    image: deeflat-is-4:0.1
    ports:
      - 9091:80
      - 9092:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=DeeFlatPassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/deeflat.pfx
    volumes:
      - C:/.aspnet/https:/https:ro