version: "3.7"
services:
    #DB
    dee-flat-db:
        container_name: dee-flat-db
        restart: unless-stopped
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=adminadmin
            - POSTGRES_DB=deeflatdb
        image: "postgres"
        hostname: dee-flat-db
        ports:
            - "5433:5432"
        volumes:
            - database-data:/var/lib/postgresql/data/
    #СУБД для проверки подключений
    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - "5051:80"
        volumes:
            - pgadmin:/root/.pgadmin
        restart: unless-stopped
    #API
    dee-flat-monolit :
        container_name: dee-flat-monolit
        depends_on:
            - dee-flat-db
            - deeflat-is-4
        image: "dee-flat-monolit"
        ports:
            - 9093:80
            - 9094:5001
        environment:
            - ASPNETCORE_URLS=https://+:5001;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=DeeFlatPassword
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/deeflat.pfx
            - "DB_ConectionString=Host=dee-flat-db;port=5432;Database=deeflatdb;Username=admin;Password=adminadmin"
        volumes:
        - C:/.aspnet/https:/https:ro
     #identity-server-4
    deeflat-is-4:
        image: deeflat-is-4:0.1
        container_name: deeflat-is-4
        ports:
        - 9091:80
        - 9092:443
        environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - ASPNETCORE_Kestrel__Certificates__Default__Password=DeeFlatPassword
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/deeflat.pfx
        volumes:
        - C:/.aspnet/https:/https:ro
    #identity-server-4-db
    deeflat-is4-db:
        container_name: deeflat-is4-db
        restart: unless-stopped
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=adminadmin
            - POSTGRES_DB=deeflat-is4-db
        image: "postgres"
        hostname: deeflat-is4-db
        ports:
            - "5434:5432"
        volumes:
            - database-is4-data:/var/lib/postgresql/data/
    #dictionary-db
    deeflat-dictionary-db:
        container_name: deeflat-dictionary-db
        restart: unless-stopped
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=adminadmin
            - POSTGRES_DB=deeflat-dictionary-db
        image: "postgres"
        hostname: deeflat-dictionary-db
        ports:
            - "5435:5432"
        volumes:
            - deeflat-dictionary-data:/var/lib/postgresql/data/
    # login guest:guest
    deeflat-rabbitmq-bus:
        image: rabbitmq:3-management
        hostname: "rabbitmq"
        labels:
            NAME: "rabbitmq"
        ports:
        - "4369:4369"
        - "5671:5671"
        - "5672:5672"
        - "25672:25672"
        - "15671:15671"
        - "15672:15672"
    #dictionary-email
    deeflat-email:
        container_name: deeflat-email
        image: "deeflat-email"
        ports:
            - 9292:80
            - 9293:5001
        environment:
            - ASPNETCORE_URLS=https://+:5001;http://+:80
    #Dee Flat Group DB
    dee-flat-group-db:
        container_name: dee-flat-group-db
        restart: unless-stopped
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=adminadmin
            - POSTGRES_DB=deeflatgroupdb
        image: "postgres"
        hostname: dee-flat-group-db
        ports:
            - "5434:5432"
        volumes:
            - dee-flat-group-db-data:/var/lib/postgresql/data/
    #Dee Flat Courses DB
    dee-flat-course-db:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
         MONGO_INITDB_ROOT_USERNAME: root
         MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        image: mongo-express
        restart: always
        ports:
        - 8082:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
volumes:
    pgadmin:
    database-data:
    database-is4-data:
    deeflat-dictionary-data:
    dee-flat-group-db-data:
